# Generated by Django 5.2.15 on 2026-08-26 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='singers/')),
                ('image_url', models.URLField()),
                ('info', models.JSONField(default=list)),
                ('info_text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='songs/')),
                ('image_url', models.URLField()),
                ('lyrics', models.JSONField(default=list)),
                ('lyrics_text', models.CharField(max_length=10000)),
                ('singers', models.ManyToManyField(related_name='songs', to='music_app.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('time', models.DateTimeField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music_app.song')),
            ],
        ),
    ]
