# Generated by Django 5.2.15 on 2026-08-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, upload_to='singer/'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='info_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, upload_to='song/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
